name = "letrocq"
defaultTargets = ["LeTrocq"]
testDriver = "test"
srcDir = "src"

# warnings as errors
leanOptions = [{ name = "warningAsError", value = true }]

[[lean_lib]]
name = "LeTrocq"

# examples of using the library, not part of the library
# The tests import them
[[lean_lib]]
name = "Examples"
globs = ["Examples.*"]

[[lean_lib]]
name = "Tests"
globs = ["Tests.*"]

[[lean_exe]]
name = "test"
root = "Tests"
